name: github-push-actions
on:
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: echo bats version
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  echo-env:
    runs-on: ubuntu-latest
    steps:
      - name: print
      - uses: actions/setup-node@v2
      - env:
          WELCOME: welcome
          MY_NAME: johe
      - run:
          echo $WELCOME $MY_NAME.